server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-83615810.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9syy04sIfJ8EUk5d7
    client-secret: pa73_wn2RjHn8pCN_JjwQhfl-cE_CU9lvl3fulyb
    scopes: openid, profile, email, offline_access
