spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HRS_RatingService
    username: postgres
    password: Rujan123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
server:
  port: 8083

okta:
  oauth2:
    issuer: https://dev-83615810.okta.com/oauth2/default
    audience: api://default
